version: '3'
services:
  app:
    container_name: "python_machine_learning"
    build:
      context: . 
      dockerfile: ./Dockerfile
    image: python_machine_learning
    ports:
      - "8888:8888"
    volumes: 
        - $PWD:/home/docker_machine_learning
    tty: true
